from .models import PipelineResult, Segment, SubtitleConfig
from .app_config import AppConfig, load_app_config, save_app_config
from .job_runner import run_project_job
from .errors import (
    CaptionFlowError,
    ConfigError,
    ExportError,
    ProviderAuthError,
    ProviderDependencyError,
    ProviderError,
    ProviderNotFoundError,
    ProviderRuntimeError,
    SubtitleEditError,
    TTSError,
    TranscriptionError,
    TranslationError,
)
from .subtitle_editor import (
    SubtitleValidationIssue,
    delete_segment,
    edit_segment_text,
    load_subtitle_draft,
    merge_segments,
    normalize_segment_order,
    save_subtitle_draft,
    shift_segment_time,
    snapshot_segments,
    split_segment,
    validate_segments,
)
from .progress import EventSink, PipelineEvent, console_event_sink, emit_event
from .providers import (
    ProviderCapabilities,
    ProviderAvailabilityCheck,
    ProviderConfig,
    ProviderResultMetadata,
    ProviderRoute,
    ProviderRouter,
    EdgeTTSProvider,
    FasterWhisperProvider,
    TTSProvider,
    TTSResult,
    TranscriptionProvider,
    TranscriptionResult,
    TranslatorProviderAdapter,
    TranslationProvider,
    TranslationResult,
    check_provider_availability,
    create_transcription_provider,
    create_translation_provider,
    create_tts_provider,
    get_provider_capabilities,
    list_provider_capabilities,
    list_provider_names,
)
from .projects import (
    JobRecord,
    Project,
    add_job,
    create_project,
    load_job_subtitle_draft,
    load_project,
    save_job_subtitle_draft,
    save_project,
    update_job_status,
)


def __getattr__(name: str):
    if name == "run_subtitle_pipeline":
        from .pipeline import run_subtitle_pipeline

        return run_subtitle_pipeline
    if name == "run_subtitle_pipeline_detailed":
        from .pipeline import run_subtitle_pipeline_detailed

        return run_subtitle_pipeline_detailed
    raise AttributeError(f"module 'subtitle_pipeline' has no attribute {name!r}")

__all__ = [
    "run_subtitle_pipeline",
    "run_subtitle_pipeline_detailed",
    "Segment",
    "SubtitleConfig",
    "PipelineResult",
    "AppConfig",
    "load_app_config",
    "save_app_config",
    "run_project_job",
    "CaptionFlowError",
    "ConfigError",
    "ExportError",
    "ProviderAuthError",
    "ProviderDependencyError",
    "ProviderError",
    "ProviderNotFoundError",
    "ProviderRuntimeError",
    "SubtitleEditError",
    "TTSError",
    "TranscriptionError",
    "TranslationError",
    "ProviderCapabilities",
    "ProviderAvailabilityCheck",
    "ProviderConfig",
    "ProviderResultMetadata",
    "ProviderRoute",
    "ProviderRouter",
    "EdgeTTSProvider",
    "FasterWhisperProvider",
    "TTSProvider",
    "TTSResult",
    "TranscriptionProvider",
    "TranscriptionResult",
    "TranslatorProviderAdapter",
    "TranslationProvider",
    "TranslationResult",
    "check_provider_availability",
    "create_transcription_provider",
    "create_translation_provider",
    "create_tts_provider",
    "get_provider_capabilities",
    "list_provider_capabilities",
    "list_provider_names",
    "JobRecord",
    "Project",
    "add_job",
    "create_project",
    "load_job_subtitle_draft",
    "load_project",
    "save_job_subtitle_draft",
    "save_project",
    "update_job_status",
    "SubtitleValidationIssue",
    "delete_segment",
    "edit_segment_text",
    "load_subtitle_draft",
    "merge_segments",
    "normalize_segment_order",
    "save_subtitle_draft",
    "shift_segment_time",
    "snapshot_segments",
    "split_segment",
    "validate_segments",
    "EventSink",
    "PipelineEvent",
    "console_event_sink",
    "emit_event",
]
